---
- hosts: webservers
  become: true
  tasks:
     - name: install apache2
       apt: name=apache2 state=present
     - name: service start
       service: name=apache2 state=started
     - name: copy index.html file
       copy: src=/opt/index.html dest=/var/www/html/